name: HudActionbar
version: '@version@'
main: dev.padrewin.hudactionbar.HudActionbar
api-version: '1.20'
authors: [ padrewin ]
website: 'https://github.com/Cold-Development/HudActionbar'
softdepend:
  - PlaceholderAPI

commands:
  hudactionbar:
    description: Main command for HudActionbar plugin
    aliases: [cb, hudactionbar, hac, hud]
    permission: "hudactionbar.version"
  reload:
    description: Reloads the HudActionbar configuration
    permission: "hudactionbar.reload"
  help:
    description: Displays help for HudActionbar commands
    permission: "hudactionbar.help"

permissions:
  hudactionbar.*:
    description: Root permission for HudActionbar plugin
    children:
      hudactionbar.reload: true
      hudactionbar.help: true
      hudactionbar.version: true

  hudactionbar.version:
    description: Grants access to view the plugin version
    default: true

  hudactionbar.reload:
    description: Grants access to reload command
    default: op

  hudactionbar.help:
    description: Grants access to help command
    default: true
